spring:
  mail:
    host: smtp.poczta.onet.pl
    port: 465
    username: arendariusztest@onet.pl
    password: Javastart1
    properties:
      mail.smtp.ssl.enable: true
      auth: true


logging:
  level:
    com.example.demo: DEBUG
